-- +migrate Up
CREATE TABLE IF NOT EXISTS `tasks` (
  id INT AUTO_INCREMENT NOT NULL,
  title VARCHAR(255),
  content VARCHAR(1024),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  PRIMARY KEY (id)
);
-- +migrate Down
DROP TABLE IF EXISTS `tasks`;