version: "3.8"

services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    hostname: db

  go:
    build:
      context: .
      target: local
      dockerfile: ./docker/go/Dockerfile
    ports:
      - 8888:8888
    tty: true
    volumes:
      - ./src:/go/src/app
volumes:
  db-store:
