version: "3.8"

services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  go:
    build:
      context: app
      target: local
    ports:
      - 8888:8888
    tty: true
    volumes:
      - ./src:/go/src/app
